### PR TITLE
Improved compilation time of WBToolbox blocks by optimizing `Blockinitialization()`

### PR DESCRIPTION
**Pull request by nunoguedelha**
This is related to https://github.com/robotology/wb-toolbox/issues/189. Refer to those issues for full details.

Improved compilation time of WBToolbox blocks by optimizing `Blockinitialization()` code:
- In `Blockinitialization()` current implementation, we first retrieve the list of all the WBT
  blocks in the model. Then we look for the closest Config block, starting from the block's
  scope, and going up in the tree.
- The optimization consisted in retrieving only the Config blocks (name under mask is `ImConfig`)
  instead of the full list. the reduced list is enough for the second regexp, when looking for
  the closest Config, since only the lines containing `ImConfig` are supposed to match the regexp.
- This change is compatible with the support of multi-config models.

### CODE REVIEW

**Comment by traversaro** [comment]
Why "Draft"?

**Comment by nunoguedelha** [comment]
I was still building superbuild with the changes. Although I know that the changed file is simply copied to the install folder, I wanted to have that check end to end, building, then running a compilation under Matlab.
But I'm having issues building the superbuild because of my recent update of homebrew I think.

Anyway we can move the PR to ready now, since it's a trivial change.

**Comment by nunoguedelha** [comment]
Well, great team work with all of you! And thx @Giulero for the stats on the code lines.

@diegoferigo I'll push force a commit to remove the reference you mentioned.

**Comment by diegoferigo** [comment]
Merged into `master` and aligned `devel`.

**Comment by nunoguedelha** [comment]
CC @gabrielenava

**Pull request merged**
