### PR TITLE
Added explicit gravity option to inverse dynamics

### PR DESCRIPTION
**Pull request by francesco-romano**
As in https://github.com/robotology/WB-Toolbox/issues/17

cc @traversaro @nunoguedelha

### CODE REVIEW

**Comment by francesco-romano** [comment]
Just wait before testing.. I discover a new feature (for me)

**Comment by francesco-romano** [comment]
Ready to be tested.
Blocks changed:
- Inverse Dynamics
- Get Bias Forces
- Gravity Compensation

**Comment by nunoguedelha** [comment]
@francesco-romano tested "Get Gravity Forces" and "Inverse Dynamics", comparing both with joint torque measurements:
- for several still positions of the legs
- for two use cases: gravity vector = [0,0,-9.8] or [3,0,-7.8]

... and it's working fine: all three measurements are always equal.

**Note**: for gravity vector = [3,0,-7.8] set in Gazebo, I set [**-3**,0,-7.8] as the simulink blocks input, considering the base frame orientation.

=> didn't test "Get Bias Forces"

**Comment by francesco-romano** [comment]
Great. So I understand I can merge it, right?

**Comment by nunoguedelha** [comment]
Tests on "Get Bias Forces" are ok. Merging.

**Pull request merged**
