### PR TITLE
Link the Yarp libraries dependencies, instead of using YARP_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by nunoguedelha**
Refer to the https://github.com/robotology/robotology-superbuild/issues/81 for more details.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
@diegoferigo , actually that was my initial intention, but I thought the new way of using Yarp dependencies was to avoid extracting directly the interface includes path, except when really required, typically when we're using SWIG for generating bindings, like in the case of `yarp-matlab-bindings`.
Since we're not using SWIG here I was going directly for the libraries linking.

**Comment by nunoguedelha** [comment]
Anyway, I'll following your suggestion.

**Comment by nunoguedelha** [comment]
@diegoferigo , done.

**Comment by diegoferigo** [comment]
> I thought the new way of using Yarp dependencies was to avoid extracting directly the interface includes path, except when really required

@nunoguedelha Yes you are right on this, but I think this is the cleanest way in this case since it is not strictly required linking any library. I prefer extracting a directory at CMake level rather than calling the linker without any reason. Thanks for the fix! :smile:

**Pull request merged**
