### PR TITLE
Export WholeBodyToolbox.slx as a 2016B SLX file

### PR DESCRIPTION
**Pull request by traversaro**
Furthermore, modify the `matlab/export_library.m` file to export that file as 2016B. 

This is done to solve https://github.com/robotology/wb-toolbox/issues/219, the problem that `WholeBodyToolbox` was not appearing in the Simulink library browser.

### CODE REVIEW

**Comment by traversaro** [comment]
Note that as I am on Ubuntu 20.04 to debug https://github.com/robotology/wb-toolbox/issues/219, I have first opened `wb-toolbox/matlab/library/exported/WBToolboxLibrary.slx` in MATLAB, I saved it as `wb-toolbox/matlab/library/WBToolboxLibrary_repository.mdl` in 2020b mdl format, and then I run the modified `matlab/export_library.m` to generate the new `wb-toolbox/matlab/library/exported/WBToolboxLibrary.slx` in MATLAB R2016b slx format.

**Comment by traversaro** [comment]
cc @CarlottaSartore @VenusPasandi @valentino-razza @nunoguedelha

**Comment by traversaro** [comment]
This was a regression of 6 days ago in https://github.com/robotology/wb-toolbox/pull/211, so it could be relevant to anyone that cloned or updated the superbuild in these period. @lrapetti @Yeshasvitvs @HosameldinMohamed @gabrielenava @Giulero .

**Review by lrapetti — APPROVED** [review]
Looks good, didn't test it though

**Comment by traversaro** [comment]
Thanks @lrapetti !

**Pull request merged**
