### PR TITLE
Switched to Yarp 3: updated interfaces and removed ConstString

### PR DESCRIPTION
**Pull request by diegoferigo**
Only minor changes are needed for the upcoming Yarp release. Fixes https://github.com/robotology/wb-toolbox/issues/119.

### CODE REVIEW

**Comment by traversaro** [comment]
I think turning the forward declaration to actual includes would permit to have a single branch of wb-toolbox compatible with both YARP 2.3.72 and YARP > 2.3.73, but that's your call. 

However, I think that enforcing the new minimum required version of YARP in https://github.com/robotology/wb-toolbox/blob/932c81cd049c7ce0c2494d60fe52bfd8c11dfd20/toolbox/CMakeLists.txt#L5 would definitely provide a clearer error in case of YARP/wb-toolbox version mismatch.

**Comment by diegoferigo** [comment]
> However, I think that enforcing the new minimum required version of YARP would definitely provide a clearer error in case of YARP/wb-toolbox version mismatch.

I already thought of this, but Yarp devel still exports `2.3.73.3` and not 3.

**Comment by traversaro** [comment]
> I already thought of this, but Yarp devel still exports 2.3.73.3 and not 3.

Exactly, while the master exports 2.3.72.* , so as YARP version configuration files use the `AnyNewerVersion` policy (https://github.com/robotology/yarp/blob/245690a2bb2b371a81efe0da2f9dbbd9f34e53b2/cmake/YarpDescribe.cmake#L82 , https://cmake.org/cmake/help/v3.8/module/CMakePackageConfigHelpers.html) having `find_package(YARP 2.3.73.3 REQUIRED)` will work fine.

**Comment by diegoferigo** [comment]
I'd prefer to keep things clear and keep forward declarations. This PR breaks Windows running on Yarp `2.*` anyway since I removed `ConstString`s, and keeping the development of wb-toolbox aligned with Yarp as we do for many repos simplifies the maintenance (especially in the occasions of big changes like this coming release).

Said this, sadly appveyor will not pass until the next binary release :thinking: Considering we still do not have any test against Yarp devel on Windows, I'm going to merge anyway.

**Comment by traversaro** [comment]
> Said this, sadly appveyor will not pass until the next binary release thinking Considering we still do not have any test against Yarp devel on Windows, I'm going to merge anyway.

Ok. Approving, but note that both this problems would not be present if we just switched to use includes in place of forward declaration.

**Comment by traversaro** [comment]
We had a similar problem with forward declaration in gazebo-yarp-plugins as Gazebo was migrating from `boost::shared_ptr` to `std::shared_ptr`, see  https://github.com/robotology/gazebo-yarp-plugins/pull/207#discussion_r43463799 .

**Comment by diegoferigo** [comment]
> note that this problem would not be present if we just switched to use includes in place of forward declaration

I see the point for the interfaces, not for the removal of `ConstString`. I didn't try, but I think that I should revert [this edit](https://github.com/robotology/wb-toolbox/pull/120/commits/807a696661ec1d9902218d6b0eed9e0a24a584d4#diff-563c9313c46a1d98fe8c205a9ec54756L271) to let windows build.

**Comment by traversaro** [comment]
> I see the point for the interfaces, not for the removal of `ConstString`.

Yep, I mean for the interfaces. Removing the  `ConstString` is a totally unrelated change.

**Comment by diegoferigo** [comment]
I gave it a try, but unfortunately despite `RobotInterface` might work, blocks that read those interfaces which are calling methods without the `2` do not work. Let's keep this broken status of Windows on current `yarp@v2.*` with `wb-toolbox@devel`. Note that this is an uncommon combination, hopefully it is just matter of a couple of weeks.

**Comment by traversaro** [comment]
Yep, no problem!

**Comment by diegoferigo** [comment]
Travis is clogged. Since Travis builds fine on my fork, I'm going to merge the PR.

**Pull request merged**
